//
// Generated file, do not edit! Created by opp_msgtool 6.1 from common/datagram/datagram.msg.
//

#ifndef __DATAGRAM_M_H
#define __DATAGRAM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Datagram;
/**
 * Class generated from <tt>common/datagram/datagram.msg:2</tt> by opp_msgtool.
 * <pre>
 * packet Datagram
 * {
 *     int senderID;
 *     double data;
 * }
 * </pre>
 */
class Datagram : public ::omnetpp::cPacket
{
  protected:
    int senderID = 0;
    double data = 0;

  private:
    void copy(const Datagram& other);

  protected:
    bool operator==(const Datagram&) = delete;

  public:
    Datagram(const char *name=nullptr, short kind=0);
    Datagram(const Datagram& other);
    virtual ~Datagram();
    Datagram& operator=(const Datagram& other);
    virtual Datagram *dup() const override {return new Datagram(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderID() const;
    virtual void setSenderID(int senderID);

    virtual double getData() const;
    virtual void setData(double data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Datagram& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Datagram& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Datagram *fromAnyPtr(any_ptr ptr) { return check_and_cast<Datagram*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATAGRAM_M_H

